router:
  http.get:
    clubs.index:
      "/clubs": ~

    clubs.search:
      "/clubs/search": ~

    clubs.sole:
      "/clubs/c{club_hid}(/{topic_hid})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer

    clubs.sole.edit:
      "/clubs/c{club_hid}/edit":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.edit.location:
      "/clubs/c{club_hid}/edit/location":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members:
      "/clubs/c{club_hid}/members":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members.owners:
      "/clubs/c{club_hid}/members/leaders":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members.blocked:
      "/clubs/c{club_hid}/members/blocked":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members.pending:
      "/clubs/c{club_hid}/members/pending":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members.log:
      "/clubs/c{club_hid}/members/log":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members.owners.confirm:
      "/clubs/c{club_hid}/confirm_owner/{secret_key}":
        club_hid:
          match: /\d+/
          type: integer
        secret_key:
          match: /[0-9a-f]+/
          type: string

    clubs.sole.unsubscribe:
      "/unsubscribe/clubs/c{club_hid}":
        club_hid:
          match: /\d+/
          type: integer

    clubs.topic:
      "/clubs/c{club_hid}/topic{topic_hid}(/page{page})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer
        page:
          match: /[1-9]\d*/
          type: integer
          default: 1

      "/clubs/c{club_hid}/topic{topic_hid}(/{post_hid})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer
        post_hid:
          match: /\d+/
          type: integer
          default: 1

    clubs.topic.unsubscribe:
      "/unsubscribe/clubs/c{club_hid}/topic{topic_hid}":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer

    search.club_sole:
      "/search_club": ~

    search.club_topic:
      "/search_club_topic": ~
