router:
  http.get:
    clubs.index:
      "/clubs": ~

    clubs.search:
      "/clubs/search": ~

    clubs.sole:
      "/clubs/c{club_hid}(/{topic_hid})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer

    clubs.sole.edit:
      "/clubs/c{club_hid}/edit":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.members:
      "/clubs/c{club_hid}/members":
        club_hid:
          match: /\d+/
          type: integer

    clubs.sole.unsubscribe:
      "/unsubscribe/clubs/c{club_hid}":
        club_hid:
          match: /\d+/
          type: integer

    clubs.topic:
      "/clubs/c{club_hid}/topic{topic_hid}(/page{page})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer
        page:
          match: /[1-9]\d*/
          type: integer
          default: 1

      "/clubs/c{club_hid}/topic{topic_hid}(/{post_hid})":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer
        post_hid:
          match: /\d+/
          type: integer
          default: 1

    clubs.topic.unsubscribe:
      "/unsubscribe/clubs/c{club_hid}/topic{topic_hid}":
        club_hid:
          match: /\d+/
          type: integer
        topic_hid:
          match: /\d+/
          type: integer

    search.club_sole:
      "/search_club": ~

    search.club_topic:
      "/search_club_topic": ~
