setting_schemas:
  usergroup:

    clubs_can_create_clubs:
      priority: 15
      category_key: clubs
      type: boolean
      default: false

    clubs_can_reply:
      priority: 20
      category_key: clubs
      type: boolean
      default: false

    clubs_can_start_topics:
      priority: 30
      category_key: clubs
      type: boolean
      default: false

    clubs_edit_max_time:
      priority: 40
      category_key: clubs
      type: number
      default: 30

    clubs_can_close_topic:
      priority: 60
      category_key: clubs
      type: boolean
      default: false

    clubs_show_ignored:
      priority: 70
      category_key: clubs
      type: boolean
      default: false

    clubs_lead_can_pin_topic:
      priority: 1000
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_edit_posts:
      priority: 1010
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_delete_topics:
      priority: 1020
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_edit_titles:
      priority: 1050
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_close_topic:
      priority: 1060
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_edit_clubs:
      priority: 1100
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_edit_club_members:
      priority: 1110
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_lead_can_edit_club_owners:
      priority: 1120
      category_key: perm_clubs_lead
      type: boolean
      default: false

    clubs_mod_can_pin_topic:
      priority: 1000
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_edit_posts:
      priority: 1010
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_delete_topics:
      priority: 1020
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_hard_delete_topics:
      priority: 1030
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_see_hard_deleted_topics:
      priority: 1040
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_edit_titles:
      priority: 1050
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_close_topic:
      priority: 1060
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_edit_clubs:
      priority: 1100
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_edit_club_members:
      priority: 1110
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_edit_club_owners:
      priority: 1120
      category_key: perm_clubs_moderate
      type: boolean
      default: false

    clubs_mod_can_add_infractions:
      priority: 2100
      category_key: perm_infractions
      type: boolean
      default: false
